### ISSUE TITLE
Tests for std::env sometimes fail on Windows

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#224]
In https://ci.appveyor.com/project/YorickPeterse/inko/builds/20831804/job/p4yx8nnooths1xdy the tests for `std::env` failed with the following error:

```
Failures:
  Test: std::env.remove Removing a non-existing environment variable
  Location: C:/projects/inko/runtime/tests/test/std/test_env.inko:41
  ObjectValue::as_string() called on a non string
```

I'm not exactly sure what is happening here, but this error suggests that somehow the environment variable name is not a String. Perhaps somehow due to concurrent access of environment variables some data gets corrupted.
